---
- hosts: demo
  connection: ssh
  become: true
  become_user: root
  tasks:
    - name: copy all files
      copy: src=/home/ec2-user/deployment.yml dest=/home/ec2-user/
    - name: delete deployment.yml
      command: kubectl delete -f /home/ec2-user/deployment.yml
    - name: delete service.yml
      command: kubectl delete -f /home/ec2-user/service.yml
    - name: apply deployment.yml
      command: kubectl apply -f /home/ec2-user/deployment.yml
    - name: apply service.yml
      command: kubectl apply -f /home/ec2-user/service.yml       
