---
- hosts: localhost
  connection: ssh
  become: true
  become_user: ec2-user
  tasks:
    - name: "Check if path exists"
      stat: path=/home/ec2-user/.local/share/helm/plugins/helm-datree
      register: result
    - name: install datree plugin
      command: helm plugin install https://github.com/datreeio/helm-datree
      when: not result.stat.exists
    - name: update
      command: helm plugin update datree  
      when: not result.stat.exists