---
- hosts: localhost
  connection: ssh
  become: true
  become_user: ec2-user
  tasks: 
    - name: "Check if helm path exists"
      stat: path=/usr/local/bin/helm
      register: result1
    - name: "install helm"
      command: wget https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz
      when: not result1.stat.exists
    - name: "untar helm"
      command: tar -xvf helm-v3.10.2-linux-amd64.tar.gz
      when: not result1.stat.exists
    - name: "mv helm"
      command: sudo mv linux-amd64/helm /usr/local/bin/helm
      when: not result1.stat.exists